# aList = [2,4,1,6,3]
# aTuple = (2,4,1,6,3)
# print(sorted(aList))
# print(aList.sort())
# print(sorted(aTuple))
# print(aTuple.sort())
# print(enumerate(aList))
# print(enumerate(aTuple))
# help(enumerate)
# print(reversed(aList))
# print(reversed(aTuple))
# print(aList.reverse())
# print(sum(aList))
# print(sum(aTuple))
# print(zip(aList))
# print(zip(aTuple))
# print(format(aList))
# print(format(aTuple))
# print('hello'.isalpha())

x, y = input('input:').split()
